/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ServiceSystemStatusOutput
    /// </summary>
    [DataContract(Name = "service.SystemStatusOutput")]
    public partial class ServiceSystemStatusOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceSystemStatusOutput" /> class.
        /// </summary>
        /// <param name="cpaasServices">cpaasServices.</param>
        /// <param name="messagingServices">messagingServices.</param>
        /// <param name="supportServices">supportServices.</param>
        public ServiceSystemStatusOutput(ServiceSystemStatusCPAASService cpaasServices = default, ServiceSystemStatusMessagingService messagingServices = default, ServiceSystemStatusSupportService supportServices = default)
        {
            this.CpaasServices = cpaasServices;
            this.MessagingServices = messagingServices;
            this.SupportServices = supportServices;
        }

        /// <summary>
        /// Gets or Sets CpaasServices
        /// </summary>
        [DataMember(Name = "cpaas_services", EmitDefaultValue = false)]
        public ServiceSystemStatusCPAASService CpaasServices { get; set; }

        /// <summary>
        /// Gets or Sets MessagingServices
        /// </summary>
        [DataMember(Name = "messaging_services", EmitDefaultValue = false)]
        public ServiceSystemStatusMessagingService MessagingServices { get; set; }

        /// <summary>
        /// Gets or Sets SupportServices
        /// </summary>
        [DataMember(Name = "support_services", EmitDefaultValue = false)]
        public ServiceSystemStatusSupportService SupportServices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceSystemStatusOutput {\n");
            sb.Append("  CpaasServices: ").Append(CpaasServices).Append("\n");
            sb.Append("  MessagingServices: ").Append(MessagingServices).Append("\n");
            sb.Append("  SupportServices: ").Append(SupportServices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
