/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ServiceE911URIInput
    /// </summary>
    [DataContract(Name = "service.E911URIInput")]
    public partial class ServiceE911URIInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceE911URIInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ServiceE911URIInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceE911URIInput" /> class.
        /// </summary>
        /// <param name="callerName">callerName.</param>
        /// <param name="uri">uri (required).</param>
        public ServiceE911URIInput(string callerName = default, string uri = default)
        {
            // to ensure "uri" is required (not null)
            if (uri == null)
            {
                throw new ArgumentNullException("uri is a required property for ServiceE911URIInput and cannot be null");
            }
            this.Uri = uri;
            this.CallerName = callerName;
        }

        /// <summary>
        /// Gets or Sets CallerName
        /// </summary>
        [DataMember(Name = "callerName", EmitDefaultValue = false)]
        public string CallerName { get; set; }

        /// <summary>
        /// Gets or Sets Uri
        /// </summary>
        [DataMember(Name = "uri", IsRequired = true, EmitDefaultValue = true)]
        public string Uri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceE911URIInput {\n");
            sb.Append("  CallerName: ").Append(CallerName).Append("\n");
            sb.Append("  Uri: ").Append(Uri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
