/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ServiceSystemStatusMessagingService
    /// </summary>
    [DataContract(Name = "service.SystemStatusMessagingService")]
    public partial class ServiceSystemStatusMessagingService : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceSystemStatusMessagingService" /> class.
        /// </summary>
        /// <param name="messagingServer">messagingServer.</param>
        public ServiceSystemStatusMessagingService(string messagingServer = default)
        {
            this.MessagingServer = messagingServer;
        }

        /// <summary>
        /// Gets or Sets MessagingServer
        /// </summary>
        [DataMember(Name = "messaging_server", EmitDefaultValue = false)]
        public string MessagingServer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceSystemStatusMessagingService {\n");
            sb.Append("  MessagingServer: ").Append(MessagingServer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
