/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ServiceVOIPTemporalRuleSetAddEditData
    /// </summary>
    [DataContract(Name = "service.VOIPTemporalRuleSetAddEditData")]
    public partial class ServiceVOIPTemporalRuleSetAddEditData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceVOIPTemporalRuleSetAddEditData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ServiceVOIPTemporalRuleSetAddEditData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceVOIPTemporalRuleSetAddEditData" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="temporalRules">temporalRules.</param>
        public ServiceVOIPTemporalRuleSetAddEditData(string name = default, List<string> temporalRules = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ServiceVOIPTemporalRuleSetAddEditData and cannot be null");
            }
            this.Name = name;
            this.TemporalRules = temporalRules;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets TemporalRules
        /// </summary>
        [DataMember(Name = "temporal_rules", EmitDefaultValue = false)]
        public List<string> TemporalRules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceVOIPTemporalRuleSetAddEditData {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TemporalRules: ").Append(TemporalRules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 128.", new [] { "Name" });
            }

            yield break;
        }
    }

}
