/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CallQueueMembershipApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CallQueueMembershipApiTests : IDisposable
    {
        private CallQueueMembershipApi instance;

        public CallQueueMembershipApiTests()
        {
            instance = new CallQueueMembershipApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CallQueueMembershipApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CallQueueMembershipApi
            //Assert.IsType<CallQueueMembershipApi>(instance);
        }

        /// <summary>
        /// Test V1AccountAccountIDQueuemembershipPost
        /// </summary>
        [Fact]
        public void V1AccountAccountIDQueuemembershipPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //ServiceVOIPQueueMembershipAddData reqBody = null;
            //var response = instance.V1AccountAccountIDQueuemembershipPost(accountID, reqBody);
            //Assert.IsType<ServiceDocsQueueMembershipOutput>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDQueuemembershipRecipientIDDisablePost
        /// </summary>
        [Fact]
        public void V1AccountAccountIDQueuemembershipRecipientIDDisablePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string recipientID = null;
            //var response = instance.V1AccountAccountIDQueuemembershipRecipientIDDisablePost(accountID, recipientID);
            //Assert.IsType<ServiceAPIResponse>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDQueuemembershipRecipientIDEnablePost
        /// </summary>
        [Fact]
        public void V1AccountAccountIDQueuemembershipRecipientIDEnablePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string recipientID = null;
            //ServiceVOIPCallQueueEnableMembershipData reqBody = null;
            //var response = instance.V1AccountAccountIDQueuemembershipRecipientIDEnablePost(accountID, recipientID, reqBody);
            //Assert.IsType<ServiceAPIResponse>(response);
        }
    }
}
