/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ChannelApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ChannelApiTests : IDisposable
    {
        private ChannelApi instance;

        public ChannelApiTests()
        {
            instance = new ChannelApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ChannelApi
            //Assert.IsType<ChannelApi>(instance);
        }

        /// <summary>
        /// Test V1AccountAccountIDChannelChannelIDGet
        /// </summary>
        [Fact]
        public void V1AccountAccountIDChannelChannelIDGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string channelID = null;
            //var response = instance.V1AccountAccountIDChannelChannelIDGet(accountID, channelID);
            //Assert.IsType<ServiceDocsChannelGetSingle>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDChannelChannelIDPost
        /// </summary>
        [Fact]
        public void V1AccountAccountIDChannelChannelIDPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string channelID = null;
            //ServiceVOIPChannelRunActionData reqBody = null;
            //var response = instance.V1AccountAccountIDChannelChannelIDPost(accountID, channelID, reqBody);
            //Assert.IsType<ServiceAPIResponse>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDChannelChannelIDPut
        /// </summary>
        [Fact]
        public void V1AccountAccountIDChannelChannelIDPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string channelID = null;
            //ServiceVOIPChannelRunMetaflowData reqBody = null;
            //var response = instance.V1AccountAccountIDChannelChannelIDPut(accountID, channelID, reqBody);
            //Assert.IsType<ServiceAPIResponse>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDChannelGet
        /// </summary>
        [Fact]
        public void V1AccountAccountIDChannelGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //var response = instance.V1AccountAccountIDChannelGet(accountID);
            //Assert.IsType<ServiceDocsChannelGetAll>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDDeviceDeviceIDChannelGet
        /// </summary>
        [Fact]
        public void V1AccountAccountIDDeviceDeviceIDChannelGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string deviceID = null;
            //var response = instance.V1AccountAccountIDDeviceDeviceIDChannelGet(accountID, deviceID);
            //Assert.IsType<ServiceDocsChannelGetAll>(response);
        }

        /// <summary>
        /// Test V1AccountAccountIDUserUserIDChannelGet
        /// </summary>
        [Fact]
        public void V1AccountAccountIDUserUserIDChannelGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountID = null;
            //string userID = null;
            //var response = instance.V1AccountAccountIDUserUserIDChannelGet(accountID, userID);
            //Assert.IsType<ServiceDocsChannelGetAll>(response);
        }
    }
}
