/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ModelFeatureMonthlySummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelFeatureMonthlySummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelFeatureMonthlySummary
        //private ModelFeatureMonthlySummary instance;

        public ModelFeatureMonthlySummaryTests()
        {
            // TODO uncomment below to create an instance of ModelFeatureMonthlySummary
            //instance = new ModelFeatureMonthlySummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelFeatureMonthlySummary
        /// </summary>
        [Fact]
        public void ModelFeatureMonthlySummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelFeatureMonthlySummary
            //Assert.IsType<ModelFeatureMonthlySummary>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'FeatureCount'
        /// </summary>
        [Fact]
        public void FeatureCountTest()
        {
            // TODO unit test for the property 'FeatureCount'
        }

        /// <summary>
        /// Test the property 'FeatureName'
        /// </summary>
        [Fact]
        public void FeatureNameTest()
        {
            // TODO unit test for the property 'FeatureName'
        }

        /// <summary>
        /// Test the property 'TransactionMonth'
        /// </summary>
        [Fact]
        public void TransactionMonthTest()
        {
            // TODO unit test for the property 'TransactionMonth'
        }

        /// <summary>
        /// Test the property 'TransactionYear'
        /// </summary>
        [Fact]
        public void TransactionYearTest()
        {
            // TODO unit test for the property 'TransactionYear'
        }
    }
}
