/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ModelsAccountOutputFullCalleridExternal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelsAccountOutputFullCalleridExternalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelsAccountOutputFullCalleridExternal
        //private ModelsAccountOutputFullCalleridExternal instance;

        public ModelsAccountOutputFullCalleridExternalTests()
        {
            // TODO uncomment below to create an instance of ModelsAccountOutputFullCalleridExternal
            //instance = new ModelsAccountOutputFullCalleridExternal();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelsAccountOutputFullCalleridExternal
        /// </summary>
        [Fact]
        public void ModelsAccountOutputFullCalleridExternalInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelsAccountOutputFullCalleridExternal
            //Assert.IsType<ModelsAccountOutputFullCalleridExternal>(instance);
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
    }
}
