/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ModelEventDailySummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelEventDailySummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelEventDailySummary
        //private ModelEventDailySummary instance;

        public ModelEventDailySummaryTests()
        {
            // TODO uncomment below to create an instance of ModelEventDailySummary
            //instance = new ModelEventDailySummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelEventDailySummary
        /// </summary>
        [Fact]
        public void ModelEventDailySummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelEventDailySummary
            //Assert.IsType<ModelEventDailySummary>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Component'
        /// </summary>
        [Fact]
        public void ComponentTest()
        {
            // TODO unit test for the property 'Component'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'TransactionCount'
        /// </summary>
        [Fact]
        public void TransactionCountTest()
        {
            // TODO unit test for the property 'TransactionCount'
        }

        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Fact]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }
    }
}
