/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProvisioningDocsDocsPingOutputData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProvisioningDocsDocsPingOutputDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProvisioningDocsDocsPingOutputData
        //private ProvisioningDocsDocsPingOutputData instance;

        public ProvisioningDocsDocsPingOutputDataTests()
        {
            // TODO uncomment below to create an instance of ProvisioningDocsDocsPingOutputData
            //instance = new ProvisioningDocsDocsPingOutputData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProvisioningDocsDocsPingOutputData
        /// </summary>
        [Fact]
        public void ProvisioningDocsDocsPingOutputDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProvisioningDocsDocsPingOutputData
            //Assert.IsType<ProvisioningDocsDocsPingOutputData>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
