/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVOIPDeviceAddEditLineKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVOIPDeviceAddEditLineKeyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVOIPDeviceAddEditLineKey
        //private ServiceVOIPDeviceAddEditLineKey instance;

        public ServiceVOIPDeviceAddEditLineKeyTests()
        {
            // TODO uncomment below to create an instance of ServiceVOIPDeviceAddEditLineKey
            //instance = new ServiceVOIPDeviceAddEditLineKey();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVOIPDeviceAddEditLineKey
        /// </summary>
        [Fact]
        public void ServiceVOIPDeviceAddEditLineKeyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVOIPDeviceAddEditLineKey
            //Assert.IsType<ServiceVOIPDeviceAddEditLineKey>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
