/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceCallflowAddEditFlowData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceCallflowAddEditFlowDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceCallflowAddEditFlowData
        //private ServiceCallflowAddEditFlowData instance;

        public ServiceCallflowAddEditFlowDataTests()
        {
            // TODO uncomment below to create an instance of ServiceCallflowAddEditFlowData
            //instance = new ServiceCallflowAddEditFlowData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceCallflowAddEditFlowData
        /// </summary>
        [Fact]
        public void ServiceCallflowAddEditFlowDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceCallflowAddEditFlowData
            //Assert.IsType<ServiceCallflowAddEditFlowData>(instance);
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Fact]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }
    }
}
