/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVOIPVoicemailMessageAddData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVOIPVoicemailMessageAddDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVOIPVoicemailMessageAddData
        //private ServiceVOIPVoicemailMessageAddData instance;

        public ServiceVOIPVoicemailMessageAddDataTests()
        {
            // TODO uncomment below to create an instance of ServiceVOIPVoicemailMessageAddData
            //instance = new ServiceVOIPVoicemailMessageAddData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVOIPVoicemailMessageAddData
        /// </summary>
        [Fact]
        public void ServiceVOIPVoicemailMessageAddDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVOIPVoicemailMessageAddData
            //Assert.IsType<ServiceVOIPVoicemailMessageAddData>(instance);
        }

        /// <summary>
        /// Test the property 'CallerIdName'
        /// </summary>
        [Fact]
        public void CallerIdNameTest()
        {
            // TODO unit test for the property 'CallerIdName'
        }

        /// <summary>
        /// Test the property 'CallerIdNumber'
        /// </summary>
        [Fact]
        public void CallerIdNumberTest()
        {
            // TODO unit test for the property 'CallerIdNumber'
        }

        /// <summary>
        /// Test the property 'Folder'
        /// </summary>
        [Fact]
        public void FolderTest()
        {
            // TODO unit test for the property 'Folder'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
    }
}
