/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceWebhookAdd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceWebhookAddTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceWebhookAdd
        //private ServiceWebhookAdd instance;

        public ServiceWebhookAddTests()
        {
            // TODO uncomment below to create an instance of ServiceWebhookAdd
            //instance = new ServiceWebhookAdd();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceWebhookAdd
        /// </summary>
        [Fact]
        public void ServiceWebhookAddInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceWebhookAdd
            //Assert.IsType<ServiceWebhookAdd>(instance);
        }

        /// <summary>
        /// Test the property 'CallbackMethod'
        /// </summary>
        [Fact]
        public void CallbackMethodTest()
        {
            // TODO unit test for the property 'CallbackMethod'
        }

        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'WebhookType'
        /// </summary>
        [Fact]
        public void WebhookTypeTest()
        {
            // TODO unit test for the property 'WebhookType'
        }
    }
}
