/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVOIPPresenceSetResetEditData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVOIPPresenceSetResetEditDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVOIPPresenceSetResetEditData
        //private ServiceVOIPPresenceSetResetEditData instance;

        public ServiceVOIPPresenceSetResetEditDataTests()
        {
            // TODO uncomment below to create an instance of ServiceVOIPPresenceSetResetEditData
            //instance = new ServiceVOIPPresenceSetResetEditData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVOIPPresenceSetResetEditData
        /// </summary>
        [Fact]
        public void ServiceVOIPPresenceSetResetEditDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVOIPPresenceSetResetEditData
            //Assert.IsType<ServiceVOIPPresenceSetResetEditData>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
    }
}
