/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVOIPDeviceAddEdit5
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVOIPDeviceAddEdit5Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVOIPDeviceAddEdit5
        //private ServiceVOIPDeviceAddEdit5 instance;

        public ServiceVOIPDeviceAddEdit5Tests()
        {
            // TODO uncomment below to create an instance of ServiceVOIPDeviceAddEdit5
            //instance = new ServiceVOIPDeviceAddEdit5();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVOIPDeviceAddEdit5
        /// </summary>
        [Fact]
        public void ServiceVOIPDeviceAddEdit5InstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVOIPDeviceAddEdit5
            //Assert.IsType<ServiceVOIPDeviceAddEdit5>(instance);
        }

        /// <summary>
        /// Test the property 'Codecs'
        /// </summary>
        [Fact]
        public void CodecsTest()
        {
            // TODO unit test for the property 'Codecs'
        }
    }
}
