/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceDocsCallDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceDocsCallDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceDocsCallDetail
        //private ServiceDocsCallDetail instance;

        public ServiceDocsCallDetailTests()
        {
            // TODO uncomment below to create an instance of ServiceDocsCallDetail
            //instance = new ServiceDocsCallDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceDocsCallDetail
        /// </summary>
        [Fact]
        public void ServiceDocsCallDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceDocsCallDetail
            //Assert.IsType<ServiceDocsCallDetail>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'NextStartKey'
        /// </summary>
        [Fact]
        public void NextStartKeyTest()
        {
            // TODO unit test for the property 'NextStartKey'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'StartKey'
        /// </summary>
        [Fact]
        public void StartKeyTest()
        {
            // TODO unit test for the property 'StartKey'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
