/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVoicemailOutputShort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVoicemailOutputShortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVoicemailOutputShort
        //private ServiceVoicemailOutputShort instance;

        public ServiceVoicemailOutputShortTests()
        {
            // TODO uncomment below to create an instance of ServiceVoicemailOutputShort
            //instance = new ServiceVoicemailOutputShort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVoicemailOutputShort
        /// </summary>
        [Fact]
        public void ServiceVoicemailOutputShortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVoicemailOutputShort
            //Assert.IsType<ServiceVoicemailOutputShort>(instance);
        }

        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

        /// <summary>
        /// Test the property 'Flags'
        /// </summary>
        [Fact]
        public void FlagsTest()
        {
            // TODO unit test for the property 'Flags'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Mailbox'
        /// </summary>
        [Fact]
        public void MailboxTest()
        {
            // TODO unit test for the property 'Mailbox'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
    }
}
