/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceE911ActiveLocationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceE911ActiveLocationStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceE911ActiveLocationStatus
        //private ServiceE911ActiveLocationStatus instance;

        public ServiceE911ActiveLocationStatusTests()
        {
            // TODO uncomment below to create an instance of ServiceE911ActiveLocationStatus
            //instance = new ServiceE911ActiveLocationStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceE911ActiveLocationStatus
        /// </summary>
        [Fact]
        public void ServiceE911ActiveLocationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceE911ActiveLocationStatus
            //Assert.IsType<ServiceE911ActiveLocationStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
