/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceAdminUserAddData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceAdminUserAddDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceAdminUserAddData
        //private ServiceAdminUserAddData instance;

        public ServiceAdminUserAddDataTests()
        {
            // TODO uncomment below to create an instance of ServiceAdminUserAddData
            //instance = new ServiceAdminUserAddData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceAdminUserAddData
        /// </summary>
        [Fact]
        public void ServiceAdminUserAddDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceAdminUserAddData
            //Assert.IsType<ServiceAdminUserAddData>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
    }
}
