/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVOIPAccountEditData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVOIPAccountEditDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVOIPAccountEditData
        //private ServiceVOIPAccountEditData instance;

        public ServiceVOIPAccountEditDataTests()
        {
            // TODO uncomment below to create an instance of ServiceVOIPAccountEditData
            //instance = new ServiceVOIPAccountEditData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVOIPAccountEditData
        /// </summary>
        [Fact]
        public void ServiceVOIPAccountEditDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVOIPAccountEditData
            //Assert.IsType<ServiceVOIPAccountEditData>(instance);
        }

        /// <summary>
        /// Test the property 'CallerId'
        /// </summary>
        [Fact]
        public void CallerIdTest()
        {
            // TODO unit test for the property 'CallerId'
        }

        /// <summary>
        /// Test the property 'DoNotDisturb'
        /// </summary>
        [Fact]
        public void DoNotDisturbTest()
        {
            // TODO unit test for the property 'DoNotDisturb'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'MusicOnHold'
        /// </summary>
        [Fact]
        public void MusicOnHoldTest()
        {
            // TODO unit test for the property 'MusicOnHold'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
    }
}
