/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceDocsWebhookGetAll
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceDocsWebhookGetAllTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceDocsWebhookGetAll
        //private ServiceDocsWebhookGetAll instance;

        public ServiceDocsWebhookGetAllTests()
        {
            // TODO uncomment below to create an instance of ServiceDocsWebhookGetAll
            //instance = new ServiceDocsWebhookGetAll();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceDocsWebhookGetAll
        /// </summary>
        [Fact]
        public void ServiceDocsWebhookGetAllInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceDocsWebhookGetAll
            //Assert.IsType<ServiceDocsWebhookGetAll>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
