/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceCampaignImportOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceCampaignImportOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceCampaignImportOutput
        //private ServiceCampaignImportOutput instance;

        public ServiceCampaignImportOutputTests()
        {
            // TODO uncomment below to create an instance of ServiceCampaignImportOutput
            //instance = new ServiceCampaignImportOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceCampaignImportOutput
        /// </summary>
        [Fact]
        public void ServiceCampaignImportOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceCampaignImportOutput
            //Assert.IsType<ServiceCampaignImportOutput>(instance);
        }

        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }

        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'MessageClass'
        /// </summary>
        [Fact]
        public void MessageClassTest()
        {
            // TODO unit test for the property 'MessageClass'
        }

        /// <summary>
        /// Test the property 'MnoStatusList'
        /// </summary>
        [Fact]
        public void MnoStatusListTest()
        {
            // TODO unit test for the property 'MnoStatusList'
        }

        /// <summary>
        /// Test the property 'SecondaryDcaSharingStatus'
        /// </summary>
        [Fact]
        public void SecondaryDcaSharingStatusTest()
        {
            // TODO unit test for the property 'SecondaryDcaSharingStatus'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
