/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceE911URIInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceE911URIInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceE911URIInput
        //private ServiceE911URIInput instance;

        public ServiceE911URIInputTests()
        {
            // TODO uncomment below to create an instance of ServiceE911URIInput
            //instance = new ServiceE911URIInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceE911URIInput
        /// </summary>
        [Fact]
        public void ServiceE911URIInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceE911URIInput
            //Assert.IsType<ServiceE911URIInput>(instance);
        }

        /// <summary>
        /// Test the property 'CallerName'
        /// </summary>
        [Fact]
        public void CallerNameTest()
        {
            // TODO unit test for the property 'CallerName'
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
    }
}
