/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceStoragePlan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceStoragePlanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceStoragePlan
        //private ServiceStoragePlan instance;

        public ServiceStoragePlanTests()
        {
            // TODO uncomment below to create an instance of ServiceStoragePlan
            //instance = new ServiceStoragePlan();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceStoragePlan
        /// </summary>
        [Fact]
        public void ServiceStoragePlanInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceStoragePlan
            //Assert.IsType<ServiceStoragePlan>(instance);
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'Aggregate'
        /// </summary>
        [Fact]
        public void AggregateTest()
        {
            // TODO unit test for the property 'Aggregate'
        }

        /// <summary>
        /// Test the property 'Modb'
        /// </summary>
        [Fact]
        public void ModbTest()
        {
            // TODO unit test for the property 'Modb'
        }

        /// <summary>
        /// Test the property 'System'
        /// </summary>
        [Fact]
        public void SystemTest()
        {
            // TODO unit test for the property 'System'
        }
    }
}
