/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceDocsPhonenumberAssignPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceDocsPhonenumberAssignPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceDocsPhonenumberAssignPayload
        //private ServiceDocsPhonenumberAssignPayload instance;

        public ServiceDocsPhonenumberAssignPayloadTests()
        {
            // TODO uncomment below to create an instance of ServiceDocsPhonenumberAssignPayload
            //instance = new ServiceDocsPhonenumberAssignPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceDocsPhonenumberAssignPayload
        /// </summary>
        [Fact]
        public void ServiceDocsPhonenumberAssignPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceDocsPhonenumberAssignPayload
            //Assert.IsType<ServiceDocsPhonenumberAssignPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Phonenumber'
        /// </summary>
        [Fact]
        public void PhonenumberTest()
        {
            // TODO unit test for the property 'Phonenumber'
        }

        /// <summary>
        /// Test the property 'ToAccount'
        /// </summary>
        [Fact]
        public void ToAccountTest()
        {
            // TODO unit test for the property 'ToAccount'
        }
    }
}
