/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceVOIPDeviceAddEdit3d
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceVOIPDeviceAddEdit3dTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceVOIPDeviceAddEdit3d
        //private ServiceVOIPDeviceAddEdit3d instance;

        public ServiceVOIPDeviceAddEdit3dTests()
        {
            // TODO uncomment below to create an instance of ServiceVOIPDeviceAddEdit3d
            //instance = new ServiceVOIPDeviceAddEdit3d();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceVOIPDeviceAddEdit3d
        /// </summary>
        [Fact]
        public void ServiceVOIPDeviceAddEdit3dInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceVOIPDeviceAddEdit3d
            //Assert.IsType<ServiceVOIPDeviceAddEdit3d>(instance);
        }

        /// <summary>
        /// Test the property 'Audio'
        /// </summary>
        [Fact]
        public void AudioTest()
        {
            // TODO unit test for the property 'Audio'
        }
    }
}
