/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceE911LocationURILegacyData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceE911LocationURILegacyDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceE911LocationURILegacyData
        //private ServiceE911LocationURILegacyData instance;

        public ServiceE911LocationURILegacyDataTests()
        {
            // TODO uncomment below to create an instance of ServiceE911LocationURILegacyData
            //instance = new ServiceE911LocationURILegacyData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceE911LocationURILegacyData
        /// </summary>
        [Fact]
        public void ServiceE911LocationURILegacyDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceE911LocationURILegacyData
            //Assert.IsType<ServiceE911LocationURILegacyData>(instance);
        }

        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Fact]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }

        /// <summary>
        /// Test the property 'Predirectional'
        /// </summary>
        [Fact]
        public void PredirectionalTest()
        {
            // TODO unit test for the property 'Predirectional'
        }

        /// <summary>
        /// Test the property 'StreetName'
        /// </summary>
        [Fact]
        public void StreetNameTest()
        {
            // TODO unit test for the property 'StreetName'
        }

        /// <summary>
        /// Test the property 'Suite'
        /// </summary>
        [Fact]
        public void SuiteTest()
        {
            // TODO unit test for the property 'Suite'
        }
    }
}
