/*
 * White Label Communications CPaas API Documentation
 *
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceCallflowOutputFull
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceCallflowOutputFullTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceCallflowOutputFull
        //private ServiceCallflowOutputFull instance;

        public ServiceCallflowOutputFullTests()
        {
            // TODO uncomment below to create an instance of ServiceCallflowOutputFull
            //instance = new ServiceCallflowOutputFull();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceCallflowOutputFull
        /// </summary>
        [Fact]
        public void ServiceCallflowOutputFullInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceCallflowOutputFull
            //Assert.IsType<ServiceCallflowOutputFull>(instance);
        }

        /// <summary>
        /// Test the property 'Featurecode'
        /// </summary>
        [Fact]
        public void FeaturecodeTest()
        {
            // TODO unit test for the property 'Featurecode'
        }

        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Fact]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Numbers'
        /// </summary>
        [Fact]
        public void NumbersTest()
        {
            // TODO unit test for the property 'Numbers'
        }

        /// <summary>
        /// Test the property 'Patterns'
        /// </summary>
        [Fact]
        public void PatternsTest()
        {
            // TODO unit test for the property 'Patterns'
        }
    }
}
